version: '3'
services:
  elixir-exc-test:
    build:
      context: .
      dockerfile: docker-image/elixir/Dockerfile
      args:
        RUN_ENV: ${RUN_ENV}
    container_name: elixir_exc_test
    volumes:
      - ./:/app
      - ~/.ssh:/root/.ssh
    environment:
      - ERL_AFLAGS=-kernel shell_history enabled
    extra_hosts:
      - "robot.sh:127.0.0.1"
    networks:
      scheduler_default:
        aliases:
          - elixir-sche
networks:
  scheduler_default:
    external: true
