name: Mix Credo

on:
  pull_request:
    branches: ["master", "dev"]

jobs:
  credo:
    name: runner / credo
    runs-on: ubuntu-latest
    container:
      image: elixir:1.15-slim
    steps:
      - name: Set up SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run credo
        run: |
          mix credo --format=oneline --only=W
