name: Mix Credo

on:
  pull_request:
    branches: ["master", "dev"]

jobs:
  credo:
    name: runner / credo
    runs-on: ubuntu-latest
    container:
      image: elixir:1.15-slim
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: credo
        uses: red-shirts/reviewdog-action-credo@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          reporter: github-pr-review # Change reporter.